### ISSUE TITLE
Modelar los datos con regresion

### ISSUE THREAD

**Issue by G00Z-G00Z** [G00Z-G00Z/lab-2.3-photosensor#5]
- [ ] Tomar las medidas reales
- [ ] Obtener los paremetros de regresion a traves de python
- [ ] Poner los paremetros de regresion en el modelo en el micro

**Comment by G00Z-G00Z** [comment]
Para poner los datos de regression, puse una libreria que se llama DistanceModel, ahi es donde encontraras la implementacion y podras poner los voeficientes @AOEli

**Comment by AOEli** [comment]
Parece que no funciona el fuzzy logic.

**Comment by G00Z-G00Z** [comment]
Lo arreglamos depues de clase
